service: mysql-proj

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256

functions:
  createUser:
    handler: src/lambdas/createUser.handler
    events:
      - http:
          path: user
          method: post
          cors: true

  getUserById:
    handler: src/lambdas/getUserById.handler
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  updateUser:
    handler: src/lambdas/updateUser.handler
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: src/lambdas/deleteUser.handler
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000